GET http://localhost:8080/first-jsf-app/api/v1/product

###

GET http://localhost:8080/first-jsf-app/api/v1/product/3

###

POST http://localhost:8080/first-jsf-app/api/v1/product
Content-Type: application/json

{
  "brandId": 2,
  "brandName": "Brand 2",
  "categoryId": 5,
  "categoryName": "Category 2",
  "id": null,
  "name": "Product 4",
  "price": 444.00
}

###

PUT http://localhost:8080/first-jsf-app/api/v1/product
Content-Type: application/json

{
  "brandId": 2,
  "brandName": "Brand 2",
  "categoryId": 5,
  "categoryName": "Category 2",
  "id": 8,
  "name": "Product 4 changed",
  "price": 3333.00
}

###

DELETE http://localhost:8080/first-jsf-app/api/v1/product/7

###

GET http://localhost:8080/first-jsf-app/api/v1/brand

###

GET http://localhost:8080/first-jsf-app/api/v1/brand/2

###

POST http://localhost:8080/first-jsf-app/api/v1/brand
Content-Type: application/json

{
  "name": "Added brand"
}

###

DELETE http://localhost:8080/first-jsf-app/api/v1/brand/5

###

GET http://localhost:8080/first-jsf-app/api/v1/category

###

GET http://localhost:8080/first-jsf-app/api/v1/category/6

###

POST http://localhost:8080/first-jsf-app/api/v1/category
Content-Type: application/json

{
  "name": "Added category"
}

###

DELETE http://localhost:8080/first-jsf-app/api/v1/brand/7

###

GET http://localhost:8080/first-jsf-app/api/v1/cart

###

POST http://localhost:8080/first-jsf-app/api/v1/cart
Content-Type: application/json

{
  "id": 1,
  "name": "Product 1",
  "price": 100.00
}

###

DELETE http://localhost:8080/first-jsf-app/api/v1/cart
Content-Type: application/json
{
    "price": 100.00,
    "product":
{
      "id": 1,
      "name": "Product 1",
      "price": 100.00
    },
    "qty": 1
  }

###

DELETE http://localhost:8080/first-jsf-app/api/v1/cart/empty
