GET http://localhost:8080/mvc-app/api/v1/user/all

###

GET http://localhost:8080/mvc-app/api/v1/user/1/id

###

POST http://localhost:8080/mvc-app/api/v1/user
Content-Type: application/json

{
  "login": "ivan_ivan",
  "email": null,
  "password": "123"
}

###

PUT http://localhost:8080/mvc-app/api/v1/user
Content-Type: application/json

{
  "id": 10,
  "login": "ivan_ivan_ivan",
  "email": null,
  "password": "123"
}